### ISSUE TITLE
About yourself

### ISSUE THREAD

**Issue by RodrigoLaraM** [MLH-Fellowship/project-dancing-ducks#2]
Add ab "About yourself" section to the website.

**Comment by gujiguj** [comment]
- Photo of yourself! (Can be a drawing if you want. Like a Mii?! I also like to use https://picrew.me/ to generate icons/avatars) (300x300?)

- About you blurb

- Socials: **LinkedIn and GitHub encouraged**, plus anything else you want

- Education: institution, major(s), graduation date (month year), courses. An icon of your university's logo would be a plus!

- Experience(s): position, company, dates (month year - month year), description (icons for educational institution and workplaces would be nice but not required! if you don't have any work experiences, you can put a club down or volunteer work if you'd like!)

- Hobbies: image, description. **Hobbies apparently need to be their own separate page, so let's try to be a little more detailed to fill up space!**

- Travel: coordinates (if possible), location, description

Also, please attach your resume if you'd like.

**Comment by gujiguj** [comment]
Photo of yourself! (Can be a drawing if you want. Like a Mii?! I also like to use https://picrew.me/ to generate icons/avatars) 
![hikingrcf2](https://user-images.githubusercontent.com/43558154/172031689-8ceda16b-a89c-4e16-b597-35cdb75a125b.jpg)

    About you blurb
> Hi, I'm Lucy Wang! I'm from Newark, DE, and I'm studying Computer Science and Japanese at Villanova University. I like learning things that pique my interest! I also like cats, snoozing, and drawing cute things.

    Socials: LinkedIn and GitHub encouraged, plus anything else you want
> [LinkedIn](https://www.linkedin.com/in/lucy-wang-a73267191/)
> [GitHub](http://github.com/gujiguj)

    Education: institution, major(s), graduation date, courses
![villanova_v](https://user-images.githubusercontent.com/43558154/172031707-ccfa54b9-e62b-4ff1-9a4d-ed980c0581af.png)
> Institution: Villanova University
> Major: Computer Science
> Graduation date: May 2023

    Experience(s): position, company, dates, description (icons for workplaces would be nice but not required! if you don't have any work experiences, you can put a club down or volunteer work if you'd like!)
![sepax_logo](https://user-images.githubusercontent.com/43558154/172031711-53ab7711-e91a-4e24-9702-18620bc17b3f.png)
> Position: IT Assistant
> Company: Sepax Technologies
> Dates: July 2020 - August 2020, May 2022 - present
> Description: Maintained network of office computers, printers, and cameras, company intranet, and company's external marketing website. Used HTML/CSS, PHP, and MySQL to update and add features to the intranet and external website. Carried out general help desk tasks (e.g. setting up new desktops, assigning emails, troubleshooting network issues, and monitoring network security). 

    Hobbies: image, description. Hobbies apparently need to be their own separate page, so let's try to be a little more detailed to fill up space!

![artwork](https://user-images.githubusercontent.com/43558154/172031983-00e3b0ef-461e-40ba-ad3c-272d54f1ad73.png)
> Name: Drawing
> Description: I've been drawing in an anime/manga style since I was very young. I like drawing cute designs and designs that I find beautiful. While I often find myself unable to think of what to draw, I become super driven when I'm drawing for other people. Nothing makes me happier than creating for others!

![genshin](https://user-images.githubusercontent.com/43558154/172032362-75c3be61-fcea-4ee0-8803-306dc9f6d574.jpg)
> Name: Gaming
> Description: I'm a casual gamer. I only own a Macbook so I can't play a lot of games, so I just dabble in some mobile games! I mainly play an RPG called Genshin Impact, but I also play some of a tower defense game called Arknights. As for computer games, I'm currently playing the indie platformer Celeste! I've also casually played Minecraft, Terraria, and Portal. 

![chronocrusade](https://user-images.githubusercontent.com/43558154/172032395-3ebd4f3f-835a-4a81-a951-231d2f018418.jpg)
> Name: Anime & Manga
> Description: I love reading manga! And I also enjoy watching anime, but since it takes more time I don't do it as often :( My favorite manga is _Chrono Crusade_! I also love _Witch Hat Atelier_ and _Frieren at the Funeral_. And my favorite anime is... it's so hard to choose! Maybe _Ouran High School Host Club..._

    Travel: coordinates (if possible), location, description
> Location: China
> Coordinates: 31.224361, 121.469170
> I visited my relatives in China when I was very young. I went to Shanghai, Xiangtan in Hunan province, and the countryside in Henan province. I don't remember much, but if you're visiting the countryside, definitely be prepared for the mosquitoes!

> Location: Taiwan
> Coordinates: 22.999727, 120.227028
> I taught English to elementary and middle school students in various schools in Tainan, Taiwan for two weeks. I know Mandarin Chinese, but it was hard even when I had a teaching partner! At one school, we did not have enough people on our team and I had to teach solo! Still, it was a very exciting experience. Taiwan is a great place to visit!

> Location: Alaska
> Coordinates: 63.129887, -151.197418 (Denali National Park)
> I traveled to Alaska with family! The highlight of our trip was visiting Denali National Park, where we got to see Mt. Denali, moose, caribou, bears, and even a few wolves (in the distance). Alaska is full of preserved nature, which is evidenced by the fact bugs still get smashed against car windshields there!

> Location: Las Vegas, NV
> Coordinates: 36.114647, -115.172813
> I visited Las Vegas but... before I was 18! So I couldn't touch any of the casinos... Las Vegas is a very shiny place with some good food! I recommend visiting Serendipity for iced hot chocolate. 

> Location: Yellowstone National Park
> Coordinates: 44.423691, -110.588516
> Yellowstone National Park is very cool. The whole park has so many thermal pools that are the most beautiful shade of blue. Our tour guide actually lost his hat in one of the pools (he did not get it back)!

**Comment by yanbmia** [comment]
> * Photo of yourself! 
![mia-mlh](https://user-images.githubusercontent.com/68654939/172028591-06156d89-5874-4a1e-922b-5001c51e0f82.jpg)
> * About you blurb
Hey, I'm Mia! I'm originally from Brooklyn, New York. I currently attend Binghamton University studying Computer Science. I'm a creative person. I love anything design and art-related. I've always been an indecisive person, but one thing I always knew I wanted to do is to travel the world.
> * Socials: **LinkedIn and GitHub encouraged**, plus anything else you want
[https://www.linkedin.com/in/yanbmia/](url)
[https://github.com/yanbmia](url)
> * Education: 
Institution: Binghamton University
Major: Computer Science
Graduation Date: May 2025
> * Experience(s): 
Position: Operations Intern
Company: Xenon Health
Dates: July 2021 - November 2021
Description: I managed several company spreadsheets, conducted crucial business research, and presented various avenues and methods to improve company outreach and communication.

>* Hobbies: 
Name: Reading
Description: I'm a staunch supporter of the library! When I was a kid I read a lot, but somewhere in middle school and high school, I grew a distaste for reading. But now I read all the time. My favorite authors are James Baldwin, Dostoevsky, and Murakami. (If you don't have a local library card, what are you doing? You must get one.)
Name: Film
Description: Is watching movies a hobby? Do I need to present my letterbox account and distinguish between films and movies to prove it? I feel like I can never pick a favorite movie. But I do love all genres--sci-fi, romance, action--maybe everything except thriller.

`Travel: coordinates (if possible), location, description `
> * Location: London
Coordinates: 51.506180, -0.120142
I swear summer doesn't exist in London. And yes, I will continue to call the Underground the subway.

> * Location: Rainham, UK
Coordinates: 51.366388, 0.611494
My aunt and cousin moved here in 2019, so of course, I had to visit. (And by visit I totally don't mean I didn't want to pay hotel fees.) 

> * Location: Trinidad and Tobago
Coordinates: 10.170945, -61.675227
My mom is from here! I've been here lots of times to see my family.

> * Location: Miami, FL
Coordinates: 25.771533, -80.192114
Went here in August...I've never experienced humidity like this before.

> * Location: Nassau, The Bahamas
Coordinates: 25.044149, -77.354166
The ocean here is unreal. I was on a cruise with my family when I was 12 and we stopped here.

> * Location: Belize
Coordinates: 17.507322, -88.203623
My mom's uncle's wife is from here! The vibes in Belize are spectacular.

> * Location: Hubei, China
Coordinates: 30.703383, 111.292291
I went only went once when I was very little to visit my dad's family. The food was very good though.

> * Location: Shanghai, China
Coordinates: 31.241374, 121.457556
This city is amazing. I really want to go back soon.

> * Location: Montreal, Canada
Coordinates: 45.498696, -73.570269
One morning, I went to have brunch and the waitress asked me what I wanted to order in French, guess you can say I'm a local. *sarcasm ;)

> * Location: Southampton, NY
Coordinates: 40.884612, -72.393004
Unfortunately, the Hamptons aren't overhyped. It's really fun here in the summer.

> * Location: Boston, MA
Coordinates: 42.358876, -71.056763
When I was a kid, my family used to take a lot of random road trips. But I'm marking Boston down because I have some funny childhood photos here.

> Also, please attach your resume if you'd like.

**Comment by gujiguj** [comment]
Rodrigo and Kelly's info is recorded on Discord! Will consolidate it here later.
