### ISSUE TITLE
Travel Map

### ISSUE THREAD

**Issue by RodrigoLaraM** [MLH-Fellowship/project-dancing-ducks#6]
Add a map of all the cool locations/countries you visited

**Comment by gujiguj** [comment]
Checkout https://www.mapbox.com/ and https://leafletjs.com/ for implementing an interactive slippy map that we can put pins and popups on.

**Comment by gujiguj** [comment]
Thinking of using leafletjs. I finished the Quickstart tutorial and it covers everything we will need for this (embedding the map and putting in pins with popups). What do you guys think? Should we look into other tools?

**Comment by yanbmia** [comment]
Leafletjs is a good option!

**Comment by gujiguj** [comment]
Leaflet turned out pretty good! Mixing Jinja and JS was a little complex but it still turned out to be fairly easy to implement! Everything should be functional now, and I can't wait to see how it looks when all our pins are in there!!

At the moment, when you open the webpage the map is kinda "centered" around the Atlantic. Is this fine? Do you guys think it should be centered somewhere else?

**Comment by yanbmia** [comment]
I feel like I don't mind the map being centered anywhere. But it might visually make more sense if we place it in the Americas.
